[package]

name = "bio"
version = "0.13.0"
authors = ["Johannes Köster <johannes.koester@tu-dortmund.de>"]
description = "A bioinformatics library for Rust. This library provides implementations of many algorithms and data structures that are useful for bioinformatics, but also in other fields."
homepage = "https://rust-bio.github.io"
repository = "https://github.com/rust-bio/rust-bio"
documentation = "https://docs.rs/bio"
readme = "README.md"
license = "MIT"

[dependencies]
csv = "0.15"
rustc-serialize = "0.3.*"
num-traits = "0.1.*"
num-integer = "0.1.*"
itertools = "0.6"
itertools-num = "0.1"
bit-vec = "0.4"
bit-set = "0.4"
nalgebra= "0.10"
lazy_static = "0.2"
serde = "1.0"
serde_derive = "1.0"
approx = "0.1"
custom_derive = "0.1"
newtype_derive = "0.1"
ordered-float = "0.5"
quick-error = "1.2"
regex = "0.2"
multimap = "0.4"

[dependencies.vec_map]
version = "0.8"
features = ["eders"]
